[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.d]
dependencies = ["clippy-beta", "build", "test"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-features"]

[tasks.clippy-beta]
toolchain = "beta"
command = "cargo"
args = ["clippy", "--all-features"]

[tasks.clippy-no-default]
command = "cargo"
args = ["clippy", "--no-default-features"]

[tasks.test-no-default]
command = "cargo"
args = ["test", "--no-default-features"]

[tasks.build-no-default]
command = "cargo"
args = ["build", "--no-default-features"]

[tasks.doc]
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
toolchain = "nightly"
command = "cargo"
args = ["doc", "--all-features", "--no-deps", "--open"]
workspace = false

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.cover]
workspace = false
command = "cargo"
args = ["tarpaulin", "-p", "cds", "--exclude-files", "fuzz/*", "--all-features", "--out", "Html"]

[tasks.c]
workspace = false
dependencies = ["cover"]
script = '''
#!/usr/bin/env bash
browse ./tarpaulin-report.html >/dev/null 2>&1 &
'''
