name: ci

on:
  push:
    branches-ignore:
      - '**-wip'
      - '**-fuzz'
  pull_request:
  schedule:
    - cron: '0 1 * * 0'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  ci:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - 1.59.0  # MSRV
        runs_on:
          - ubuntu-latest
        feature:
          - all
          - ''
          - default
          - std
          - alloc
          - arrayvec
          - arrayvec,std
          - arraystring
          - arraystring,alloc
          - arraystring,std
          - smallvec
          - smallvec,std
          - smallstring
          - smallstring,std
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt,clippy

      - name: build cds
        if: ${{ matrix.feature != 'all' && matrix.feature != '' }}
        run: cargo build --no-default-features --features ${{ matrix.feature }}

      - name: build all cds
        if: ${{ matrix.feature == 'all' }}
        run: cargo build --all-features

      - name: build no-default-features cds
        if: ${{ matrix.feature == '' }}
        run: cargo build --no-default-features

      - name: test cds
        if: ${{ matrix.feature != 'all' && matrix.feature != '' }}
        run: cargo test --no-default-features --features ${{ matrix.feature }}

      - name: test all cds
        if: ${{ matrix.feature == 'all' }}
        run: cargo test --all-features

      - name: test no-default-features cds
        if: ${{ matrix.feature == '' }}
        run: cargo test --no-default-features

      - name: lint cds
        if: ${{ matrix.feature != 'all' && matrix.feature != '' }}
        run: cargo clippy --no-default-features --features ${{ matrix.feature }} --all-targets

      - name: lint all cds
        if: ${{ matrix.feature == 'all' }}
        run: cargo clippy --all-features --all-targets

      - name: lint no-default-features cds
        if: ${{ matrix.feature == '' }}
        run: cargo clippy --no-default-features --all-targets

  common-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: format all
        run: cargo fmt -- --check
      - name: doc cds
        env:
          RUSTDOCFLAGS: "--cfg docsrs"
        run: cargo doc --all-features --no-deps

  coverage:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v3
      - name: tarpaulin
        run: cargo +nightly tarpaulin -p cds --exclude-files fuzz/* --all-features --out html
      - uses: actions/upload-artifact@v3
        with:
          name: tarpaulin-report.html
          path: tarpaulin-report.html
