name: fuzz

on:
  push:
    branches:
      - '**-fuzz'
  schedule:
    - cron: '0 1,18 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview,rust-src

      - name: install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: install rustfilt
        run: cargo install rustfilt

      - name: fuzz arrayvec
        run: cargo fuzz run arrayvec -- -max_total_time=900 -jobs=2 -workers=2 -verbosity=0 -max_len=16192

      - name: fuzz arraystring
        run: cargo fuzz run arraystring -- -max_total_time=900 -jobs=2 -workers=2 -verbosity=0 -max_len=16192

      - name: fuzz smallvec
        run: cargo fuzz run smallvec -- -max_total_time=900 -jobs=2 -workers=2 -verbosity=0 -max_len=16192

      - name: cover arrayvec
        run: cargo fuzz coverage arrayvec

      - name: cover arraystring
        run: cargo fuzz coverage arraystring

      - name: cover smallvec
        run: cargo fuzz coverage smallvec

      - id: find_llvmcov
        name: find llvm-cov
        run: |
          LLVM_COV=$(find ~ -name "llvm-cov")
          echo "Found llvm-cov: $LLVM_COV"
          echo "llvmcov=$LLVM_COV" >> $GITHUB_OUTPUT
        shell: bash

      - name: generate arrayvec.coverage.html
        run: >
          ${{ steps.find_llvmcov.outputs.llvmcov }} show target/x86_64-unknown-linux-gnu/release/arrayvec
          --format html --instr-profile=fuzz/coverage/arrayvec/coverage.profdata --Xdemangler=rustfilt >
          arrayvec.fuzz.coverage.html

      - name: generate arraystring.coverage.html
        run: >
          ${{ steps.find_llvmcov.outputs.llvmcov }} show target/x86_64-unknown-linux-gnu/release/arraystring
          --format html --instr-profile=fuzz/coverage/arraystring/coverage.profdata --Xdemangler=rustfilt >
          arraystring.fuzz.coverage.html

      - name: generate smallvec.coverage.html
        run: >
          ${{ steps.find_llvmcov.outputs.llvmcov }} show target/x86_64-unknown-linux-gnu/release/smallvec
          --format html --instr-profile=fuzz/coverage/smallvec/coverage.profdata --Xdemangler=rustfilt >
          smallvec.fuzz.coverage.html

      - uses: actions/upload-artifact@v2
        with:
          name: arrayvec.fuzz.coverage.html
          path: arrayvec.fuzz.coverage.html

      - uses: actions/upload-artifact@v2
        with:
          name: arraystring.fuzz.coverage.html
          path: arraystring.fuzz.coverage.html

      - uses: actions/upload-artifact@v2
        with:
          name: smallvec.fuzz.coverage.html
          path: smallvec.fuzz.coverage.html
