name: fuzz

on:
  push:
    branches:
      - '**-fuzz'
  schedule:
    - cron: '0 1,18 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview,rust-src

      - name: install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: install rustfilt
        run: cargo install rustfilt

      - name: fuzz arrayvec
        run: cargo fuzz run arrayvec -- -max_total_time=900 -jobs=2 -workers=2 -verbosity=0 -max_len=16192

      - name: fuzz arraystring
        run: cargo fuzz run arraystring -- -max_total_time=900 -jobs=2 -workers=2 -verbosity=0 -max_len=16192

      - name: fuzz smallvec
        run: cargo fuzz run smallvec -- -max_total_time=900 -jobs=2 -workers=2 -verbosity=0 -max_len=16192
