name: miri

on:
  push:
    branches-ignore:
      - '**-wip'
      - '**-fuzz'
  pull_request:
  schedule:
    - cron: '0 1 * * 0'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings
  MIRIFLAGS: -Zmiri-backtrace=full

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - id: find_miri
        run: |
          MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
          echo "Found miri at: $MIRI_NIGHTLY"
          echo "miri=$MIRI_NIGHTLY" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ steps.find_miri.outputs.miri }}
          components: miri,rust-src

      - name: test all cds
        run: cargo miri test --all-features
