name: miri

on:
  push:
    branches-ignore:
      - '**-wip'
      - '**-fuzz'
  pull_request:
  schedule:
    - cron: '0 1 * * 0'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings
  MIRIFLAGS: -Zmiri-backtrace=full

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - id: find_miri
        run: |
          MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
          echo "Found miri at: $MIRI_NIGHTLY"
          echo "::set-output name=miri::$MIRI_NIGHTLY"
        shell: bash

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ steps.find_miri.outputs.miri }}
          override: true
          components: miri, rust-src

      - uses: actions-rs/cargo@v1
        name: test all cds
        with:
          command: miri
          args: test --all-features
