name: miri

on:
  push:
    branches-ignore:
      - '**-wip'
      - '**-fuzz'
  pull_request:
  schedule:
    - cron: '0 1 * * 0'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  ci:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        runs_on:
          - ubuntu-latest
        feature:
          - all
          - ''
          - default
          - std
          - alloc
          - arrayvec
          - arrayvec,std
          - arraystring
          - arraystring,alloc
          - arraystring,std
    steps:
      - id: find_miri
        run: |
          MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
          echo "Found miri at: $MIRI_NIGHTLY"
          echo "::set-output name=miri::$MIRI_NIGHTLY"
        shell: bash

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ steps.find_miri.outputs.miri }}
          override: true
          components: miri, rust-src

      - uses: actions-rs/cargo@v1
        name: test cds
        if: ${{ matrix.feature != 'all' && matrix.feature != '' }}
        with:
          command: miri
          args: test --no-default-features --features ${{ matrix.feature }}

      - uses: actions-rs/cargo@v1
        name: test all cds
        if: ${{ matrix.feature == 'all' }}
        with:
          command: miri
          args: test --all-features

      - uses: actions-rs/cargo@v1
        name: test no-default-features cds
        if: ${{ matrix.feature == '' }}
        with:
          command: miri
          args: test --no-default-features
